### ISSUE TITLE
semmle project creation request

### ISSUE THREAD

**Issue by kowthamthermofisher** [kowthamthermofisher/ultchestrepo#1]
```yaml
project-name: ultchest270522
programming-language: cpp
sha-id: ca2e67779
```
